Caching

diff --git a/.github/workflows/testing.yaml b/.github/workflows/testing.yaml
--- a/.github/workflows/testing.yaml
+++ b/.github/workflows/testing.yaml
@@ -156,7 +156,6 @@ jobs:
       - name: Terraform Init
         id: tf_init
         run: |
-            set -o xtrace
             declare -a tf_init
             rtn_chk=0
             init_dir=$(pwd)
@@ -328,72 +327,73 @@ jobs:
               ```
               </details>
 
-      - name: Trivy config scan
-        id: trivy
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-            declare -a trivy_scan
-            declare -A trivy_ignored
-            rtn_chk=0
+      # - name: Trivy config scan
+      #   id: trivy
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #   run: |
+      #       set -o xtrace
+      #       declare -a trivy_scan
+      #       declare -A trivy_ignored
+      #       rtn_chk=0
             
-            which trivy
+      #       which trivy
             
-            while read -r tf_dir; do
-              if [ -d "$tf_dir" ]; then
-                rtn_val="$(trivy config "${tf_dir}" 2>&1 || true)"
-                trivy_ignored["$tf_dir"]="$(echo "$rtn_val" | grep 'Ignore finding' | sed 's/^.*\]/   /g')"
-                trivy_scan+=("$(echo "$rtn_val" | grep -v 'INFO')")
-              else
-                trivy_scan+=("Unable to check directory: '${tf_dir}'")
-              fi
-            done <<< '${{ steps.pr_details.outputs.changed_dirs }}'
+      #       while read -r tf_dir; do
+      #         if [ -d "$tf_dir" ]; then
+      #           rtn_val="$(trivy config "${tf_dir}" 2>&1 || true)"
+      #           trivy_ignored["$tf_dir"]="$(echo "$rtn_val" | grep 'Ignore finding' | sed 's/^.*\]/   /g')"
+      #           trivy_scan+=("$(echo "$rtn_val" | grep -v 'INFO')")
+      #         else
+      #           trivy_scan+=("Unable to check directory: '${tf_dir}'")
+      #         fi
+      #       done <<< '${{ steps.pr_details.outputs.changed_dirs }}'
 
-            output=$(printf "%s\n" "${trivy_scan[@]}")
-            ignored=""
-            for key in "${!trivy_ignored[@]}"; do
-              if [ "$(echo "${trivy_ignored[$key]}" | tr -d '\s' | tr -d '\n')" != "" ]; then
-                ignored+="Module: $key \n${trivy_ignored[$key]}\n\n"
-              fi
-            done
+      #       output=$(printf "%s\n" "${trivy_scan[@]}")
+      #       ignored=""
+      #       for key in "${!trivy_ignored[@]}"; do
+      #         if [ "$(echo "${trivy_ignored[$key]}" | tr -d '\s' | tr -d '\n')" != "" ]; then
+      #           ignored+="Module: $key \n${trivy_ignored[$key]}\n\n"
+      #         fi
+      #       done
 
-            if [ "$(echo "$output" | tr -d '\s' | tr -d '\n')" != "" ]; then
-              rtn_chk=1
-            fi
+      #       if [ "$(echo "$output" | tr -d '\s' | tr -d '\n')" != "" ]; then
+      #         rtn_chk=1
+      #       fi
 
-            echo "exit=${rtn_chk}"  >> "$GITHUB_OUTPUT"
-            {
-              echo "output<<EOF"
-              echo "$output"
-              echo "EOF"
+      #       echo "exit=${rtn_chk}"  >> "$GITHUB_OUTPUT"
+      #       {
+      #         echo "output<<EOF"
+      #         echo "$output"
+      #         echo "EOF"
 
-              echo "ignored<<EOF"
-              echo -e "$ignored"
-              echo "EOF"
-            }  >> "$GITHUB_OUTPUT"
+      #         echo "ignored<<EOF"
+      #         echo -e "$ignored"
+      #         echo "EOF"
+      #       }  >> "$GITHUB_OUTPUT"
 
-            echo "Exit: ${rtn_chk}"
-            echo "Ignored: ${ignored}"
-            echo "Output: ${output}"
+      #       echo "Exit: ${rtn_chk}"
+      #       echo "Ignored: ${ignored}"
+      #       echo "Output: ${output}"
 
-      - name: Fail on Trivy security scan
-        uses: ./.github/actions/pr-comment
-        if: steps.trivy.outputs.exit != 0
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          commit_sha: ${{ github.event.after }}
-          fail_run: true
-          update_existing: true
-          comment_capture: '## Terraform Module Release'
-          comment: |
-              ## Terraform Module Release
+      # - name: Fail on Trivy security scan
+      #   uses: ./.github/actions/pr-comment
+      #   if: steps.trivy.outputs.exit != 0
+      #   with:
+      #     token: ${{ secrets.GITHUB_TOKEN }}
+      #     commit_sha: ${{ github.event.after }}
+      #     fail_run: true
+      #     update_existing: true
+      #     comment_capture: '## Terraform Module Release'
+      #     comment: |
+      #         ## Terraform Module Release
 
-              <details>
-              <summary>
-              ### Trivy scan results
-              </summary>
+      #         <details>
+      #         <summary>
+      #         ### Trivy scan results
+      #         </summary>
               
-              ```
-              ${{ steps.trivy.outputs.output }}
-              ```
-              </details>
+      #         ```
+      #         ${{ steps.trivy.outputs.output }}
+      #         ```
+      #         </details>
